version: '3'

services:
  server:
    build: ./docker
    ports:
      - 8000:8000
    volumes:
      - ./python:/workspace
      - ./script:/script
    working_dir: /workspace
    command: bash /script/start.sh

